import { ChangeDetectionStrategy, Component, computed, signal } from '@angular/core';
import { IconComponent } from '../../shared/components/icon/icon.component';

interface GlossaryTerm { term: string; definition: string; }

const TERMS: GlossaryTerm[] = [
  { term: 'Ask',             definition: 'The lowest price a seller is willing to accept for an asset.' },
  { term: 'Bid',             definition: 'The highest price a buyer is willing to pay for an asset.' },
  { term: 'Breakout',        definition: 'When a price moves beyond a defined support or resistance level with increased volume.' },
  { term: 'Bull market',     definition: 'A market condition where prices are rising or expected to rise, typically by 20% or more from recent lows.' },
  { term: 'Bear market',     definition: 'A market condition where prices fall 20% or more from recent highs, often accompanied by pessimism.' },
  { term: 'Candlestick',     definition: 'A chart type that shows a security\'s open, high, low, and close price for a given period.' },
  { term: 'Diversification', definition: 'Spreading investments across various assets to reduce exposure to any single asset\'s risk.' },
  { term: 'Drawdown',        definition: 'The peak-to-trough decline in portfolio value during a specific period, measuring risk and volatility.' },
  { term: 'EMA',             definition: 'Exponential Moving Average — a moving average that gives more weight to recent data points.' },
  { term: 'Float',           definition: 'The number of shares of a company available for public trading.' },
  { term: 'Gap',             definition: 'A break between prices on a chart where no trading occurred, usually caused by news events.' },
  { term: 'Hedge',           definition: 'An investment to reduce the risk of adverse price movements in an existing position.' },
  { term: 'Liquidity',       definition: 'How easily an asset can be bought or sold without affecting its price.' },
  { term: 'Long',            definition: 'Buying an asset with the expectation that its price will rise.' },
  { term: 'Margin',          definition: 'Borrowed funds from a broker to purchase assets, magnifying both gains and losses.' },
  { term: 'Market cap',      definition: 'Total market value of a company\'s outstanding shares (price × shares outstanding).' },
  { term: 'MACD',            definition: 'Moving Average Convergence Divergence — a trend-following momentum indicator.' },
  { term: 'Order book',      definition: 'A real-time list of buy and sell orders for an asset at various price levels.' },
  { term: 'P&L',             definition: 'Profit and Loss — the net gain or loss of a trade or portfolio over a period.' },
  { term: 'Paper trading',   definition: 'Simulated trading using virtual money to practise without financial risk.' },
  { term: 'Portfolio',       definition: 'A collection of financial assets held by an individual or institution.' },
  { term: 'Position',        definition: 'The amount of an asset held in a portfolio, long or short.' },
  { term: 'Resistance',      definition: 'A price level where selling pressure historically prevents further price increases.' },
  { term: 'RSI',             definition: 'Relative Strength Index — a momentum indicator measuring the speed and magnitude of price changes, scaled 0–100.' },
  { term: 'Short',           definition: 'Selling a borrowed asset expecting the price to fall, then buying back at a lower price.' },
  { term: 'Slippage',        definition: 'The difference between the expected fill price and the actual fill price of an order.' },
  { term: 'SMA',             definition: 'Simple Moving Average — the arithmetic mean of prices over a specified period.' },
  { term: 'Spread',          definition: 'The difference between the bid and ask price of an asset.' },
  { term: 'Stop-loss',       definition: 'An order to sell an asset once it reaches a specified price, limiting further loss.' },
  { term: 'Support',         definition: 'A price level where buying pressure historically prevents further price declines.' },
  { term: 'Ticker',          definition: 'A unique symbol assigned to a publicly traded company (e.g. AAPL for Apple).' },
  { term: 'Trend',           definition: 'The general direction in which the price of an asset is moving.' },
  { term: 'Volatility',      definition: 'The degree of variation in price over time, often measured by standard deviation.' },
  { term: 'Volume',          definition: 'The number of shares or contracts traded in a security during a given period.' },
  { term: 'Win rate',        definition: 'The percentage of trades that result in a profit, calculated as wins / total trades × 100.' },
  { term: 'Yield',           definition: 'The income generated by an investment, expressed as a percentage of cost or current value.' },
];

@Component({
  selector: 'app-academy-glossary',
  standalone: true,
  imports: [IconComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="page">
      <header class="page-head">
        <div>
          <span class="eyebrow">Academy</span>
          <h1 class="page-title">Trading glossary</h1>
          <p class="page-sub">{{ filtered().length }} terms</p>
        </div>
      </header>

      <!-- Search -->
      <div class="search-wrap">
        <app-icon name="search" [size]="14"/>
        <input
          type="text"
          class="search-input"
          placeholder="Search terms…"
          [value]="query()"
          (input)="query.set($any($event.target).value)"
        />
      </div>

      <!-- Alphabet index -->
      @if (!query()) {
        <div class="alpha-index">
          @for (letter of alphabet; track letter) {
            <a [href]="'#letter-' + letter" class="alpha-link" [class.has-terms]="hasLetter(letter)">{{ letter }}</a>
          }
        </div>
      }

      <!-- Terms list -->
      <div class="terms-list">
        @for (group of groups(); track group.letter) {
          <section [id]="'letter-' + group.letter" class="term-group">
            <h2 class="group-letter">{{ group.letter }}</h2>
            @for (t of group.terms; track t.term) {
              <div class="term-row">
                <dt class="term-name">{{ t.term }}</dt>
                <dd class="term-def">{{ t.definition }}</dd>
              </div>
            }
          </section>
        }
      </div>

      @if (filtered().length === 0) {
        <p class="no-results">No terms matching "{{ query() }}".</p>
      }
    </div>
  `,
  styleUrl: './academy-glossary.component.css',
})
export class AcademyGlossaryComponent {
  protected readonly query = signal('');

  protected readonly alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');

  protected readonly filtered = computed(() => {
    const q = this.query().toLowerCase();
    return q ? TERMS.filter(t => t.term.toLowerCase().includes(q) || t.definition.toLowerCase().includes(q)) : TERMS;
  });

  protected readonly groups = computed(() => {
    const map = new Map<string, GlossaryTerm[]>();
    for (const t of this.filtered()) {
      const letter = t.term[0].toUpperCase();
      const group = map.get(letter) ?? [];
      group.push(t);
      map.set(letter, group);
    }
    return [...map.entries()].map(([letter, terms]) => ({ letter, terms })).sort((a, b) => a.letter.localeCompare(b.letter));
  });

  protected hasLetter(letter: string): boolean {
    return TERMS.some(t => t.term[0].toUpperCase() === letter);
  }
}
